Event:
    type: entity
    table: event
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        titre:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        description:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        datecreation:
            type: date
            nullable: false
            column: dateCreation
        adresse:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        nmbremax:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: nmbreMax
        category:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        image:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
    lifecycleCallbacks: {  }
