Reclamation:
    type: entity
    table: reclamation
    indexes:
        postId:
            columns:
                - postId
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        subject:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        description:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
    manyToOne:
        postid:
            targetEntity: Postsforum
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                postId:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
