Freelancer:
    type: entity
    table: freelancer
    indexes:
        userId:
            columns:
                - userId
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        userid:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: userId
        languages:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        minhourlyfee:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: minHourlyFee
        gender:
            type: integer
            nullable: false
            options:
                unsigned: false
        cvlink:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: cvLink
        maxhourlyfee:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: maxHourlyFee
        ranking:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
    lifecycleCallbacks: {  }
