Questions:
    type: entity
    table: questions
    indexes:
        fk_test:
            columns:
                - testID
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        testid:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: testID
        question:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        bonnerep:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: bonneRep
    lifecycleCallbacks: {  }
