Tasks:
    type: entity
    table: tasks
    indexes:
        projectId:
            columns:
                - projectId
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        description:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
    manyToOne:
        projectid:
            targetEntity: Projects
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                projectId:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
