Test:
    type: entity
    table: test
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        score:
            type: integer
            nullable: false
            options:
                unsigned: false
        duree:
            type: time
            nullable: false
        type:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        nom:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        description:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
    lifecycleCallbacks: {  }
