Users:
    type: entity
    table: users
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        firstname:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: firstName
        lastname:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: lastName
        email:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        password:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        role:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        rating:
            type: integer
            nullable: false
            options:
                unsigned: false
        phone:
            type: integer
            nullable: false
            options:
                unsigned: false
        region:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        description:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        picturepath:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: picturePath
        state:
            type: integer
            nullable: false
            options:
                unsigned: false
    lifecycleCallbacks: {  }
